# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-aircraft-design',
                'doc_host': 'https://matbrunt.github.io',
                'git_url': 'https://github.com/matbrunt/nbdev-aircraft-design',
                'lib_path': 'nbdev_aircraft_design'},
  'syms': {'nbdev_aircraft_design.core': {'nbdev_aircraft_design.core.foo': ('core.html#foo', 'nbdev_aircraft_design/core.py')}}}
